# Netlify Configuration for Mahaveer Bhavan
# This file configures build settings and redirects for proper SPA routing

[build]
  # Build command
  command = "npm run build"

  # Output directory (Vite default)
  publish = "dist"

  # Set Node.js version
  [build.environment]
    NODE_VERSION = "18"

# Redirect all requests to index.html for client-side routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Development context (for preview deployments)
[context.deploy-preview]
  command = "npm run build"

# Production context
[context.production]
  command = "npm run build"

# Branch deploy context
[context.branch-deploy]
  command = "npm run build"

# Environment variables (these should be set in Netlify UI)
# VITE_SUPABASE_URL = "your-supabase-url"
# VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key"
